services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000-8009:8000-8009"
    env_file:
        - .env
    depends_on:
        - postgres
    volumes:
        - ./images:/app/images
        - ./logs:/app/logs
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      # - "80:80" # http
      # - "443:443" # https
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/:/usr/share/nginx/html
      - ./images:/usr/share/nginx/images:ro
    restart: always

  db:
    image: postgres:17
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/1-init.sql:/docker-entrypoint-initdb.d/1-init.sql:ro

  backup:
    image: postgres:17
    container_name: backup
    environment:
      PGPASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backups:/backups
    depends_on:
      - postgres
    entrypoint: [ "sh", "/backups/auto_backup.sh" ]

volumes:
  postgres_data:
  
