events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

     upstream serv_backend {
        server backend:8000;
        server backend:8001;
        server backend:8002;
        server backend:8003;
        server backend:8004;
        server backend:8005;
        server backend:8006;
        server backend:8007;
        server backend:8008;
        server backend:8009;
    }


    server {
        listen 80;
        server_name localhost;

       location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /images/ {
            alias /usr/share/nginx/images/;
            access_log off;
            expires 30d;
        }

        location /api/ {
            proxy_pass http://serv_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            client_max_body_size 5M;
        }

    }
}